### PR TITLE
[re #67] moved Post level setting back to PostService

### LINKED ISSUE #67: Post level set incorrectly to 1 for root posts
Under the hood, Hibernate uses `Post.setPost()` setter which (after its modification in #59) increments post's level as well. As a result, a new post with no parent is stored with level 1. Consequently, named query `Post.getBasePostsByDiscussion` fails to load the new post.

Solution would be to move the level setting back to `PostService`.

### PR DESCRIPTION
**Pull request by fidransky**
Resolves #67

### CODE REVIEW

File: discussment-core/src/main/java/org/danekja/discussment/core/service/imp/DefaultPostService.java [hunk 1]
```diff
@@ -64,6 +64,7 @@ public Post getPostById(long postId) throws AccessDeniedException {
 
     public Post sendReply(Post reply, Post post) throws AccessDeniedException {
         reply.setPost(post);
+        reply.setLevel(post.getLevel() + 1);
```
Comment (danekja) [inline discussment-core/src/main/java/org/danekja/discussment/core/service/imp/DefaultPostService.java]: Actually correct place for this would be then extra method Post.setAsReply(Post parent) which would call setPost and setLevel.

The Post entity needs to own its state.

Comment (fidransky) [reply discussment-core/src/main/java/org/danekja/discussment/core/service/imp/DefaultPostService.java]: True. Where is a good place to test it? Integration test?
