### PR TITLE
re #71: hide and revoke use of UI components for anonymous users

### LINKED ISSUE #71: Add support for anonymous users
Currently, when `UserService#getCurrentlyLoggedUser()` returns `null`, Discussment simply crashes. Anonymous users should be able to view discussions/posts at least - ideally their priviledges should be directed by permissions.

### PR DESCRIPTION
**Pull request by fidransky**
reimplemented #72 fixes #71

### CODE REVIEW

File: discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java [hunk 1]
```diff
@@ -144,7 +141,7 @@ public boolean canAddPost(IDiscussionUser user, Discussion discussion) {
     public boolean canEditPost(IDiscussionUser user, Post post){
         if (user == null) {
             return false;
-        } else if (Objects.equals(user.getDiscussionUserId(), post.getUserId())) {
```
Comment (danekja) [inline discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java]: Why this change? AFAIK these are equal with the differenc that use of Objects.equals prevents NPEs in case any of the compared objects is null.

File: discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java [hunk 2]
```diff
@@ -159,7 +156,7 @@ public boolean canEditPosts(IDiscussionUser user, Discussion discussion) {
     public boolean canRemovePost(IDiscussionUser user, Post post){
         if (user == null) {
             return false;
-        } else if (Objects.equals(user.getDiscussionUserId(), post.getUserId())) {
```
Comment (danekja) [inline discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java]: Why this change? AFAIK these are equal with the differenc that use of Objects.equals prevents NPEs in case any of the compared objects is null.

File: discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java [hunk 3]
```diff
@@ -174,7 +171,7 @@ public boolean canRemovePosts(IDiscussionUser user, Discussion discussion) {
     public boolean canViewPost(IDiscussionUser user, Post post) {
         if (user == null) {
             return false;
-        } else if (Objects.equals(user.getDiscussionUserId(), post.getUserId())) {
```
Comment (danekja) [inline discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java]: Why this change? AFAIK these are equal with the differenc that use of Objects.equals prevents NPEs in case any of the compared objects is null.

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/form/TopicForm.java [hunk 4]
```diff
@@ -61,16 +67,18 @@ public void setTopicService(TopicService topicService) {
...
+            Topic topic = topicService.createTopic(categoryModel.getObject(), topicModel.getObject());
+
+            if (!accessControlService.canAddDiscussion(topic)) {
+                permissionService.configureDiscussionPermissions(userService.getCurrentlyLoggedUser(), topic, new PermissionData(true, false, false, true));
             }
 
-            topicModel.setObject(new Topic());
-            setResponsePage(getPage().getPageClass(), getPage().getPageParameters());
+        } catch (AccessDeniedException e) {
+            // todo: not yet impemented
```
Comment (danekja) [inline discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/form/TopicForm.java]: Todo?

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java [hunk 5]
```diff
@@ -80,32 +90,46 @@ protected void populateItem(final ListItem<Discussion> listItem) {
...
+                }
+
                 listItem.add(createRemoveDiscussionLink(listItem.getModel()));
             }
         });
+
+        add(new PasswordForm("passwordForm", discussionModel, new Model<>(new Discussion()), userService, accessControlService, permissionService, discussionService));
+    }
+
+    private Post getLastPost(Discussion discussion) {
```
Comment (danekja) [inline discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java]: I believe this method should be replaced by a Model which will be passed to Label (and either show something or not)

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java [hunk 6]
```diff
@@ -80,32 +90,46 @@ protected void populateItem(final ListItem<Discussion> listItem) {
...
+        try {
+            return postService.getLastPost(discussion);
+        } catch (AccessDeniedException e) {
+            return null;
+        }
     }
 
+    private IDiscussionUser getPostAuthor(Post post) {
```
Comment (danekja) [inline discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java]: I believe this method should be replaced by a Model which will be passed to Label (and either show something or not)

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/panel/postReputation/PostReputationPanel.java [hunk 7]
```diff
@@ -62,21 +66,21 @@ protected void onInitialize() {
...
+        add(new PostReputationForm("prform", postModel, postService, postReputationService, userService, accessControlService));
 
         Label liked = new Label("liked");
-        liked.setVisible(false);
+        add(liked);
 
-        if (postReputationService.userVotedOn(userService.getCurrentlyLoggedUser(), postModel.getObject())){
-            if (postReputationService.userLiked(userService.getCurrentlyLoggedUser(), postModel.getObject())){
-                liked = new Label("liked", new ResourceModel("postReputation.liked"));
+        if (!userService.isGuest() && postReputationService.userVotedOn(userService.getCurrentlyLoggedUser(), postModel.getObject())) {
```
Comment (danekja) [inline discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/panel/postReputation/PostReputationPanel.java]: I believe this should be replaced by a Model which will be passed to the Label(liked) (and inside will check what to show) based on postReputationService.getVote result.

Visibility of liked Label should be decided by onConfigure method override which will check isGuest and userVotedOn to decide whether to set visible or not.

Current implementation wont work properly when e.g. user´s session expires.

File: discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java (hunk 1 above)
Comment (fidransky) [reply discussment-core/src/main/java/org/danekja/discussment/core/accesscontrol/service/impl/PermissionService.java]: I don't remember my original reasoning but while `Objects.equals` is safer overall, in this case `post.getUserId()` should never be null.

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/form/TopicForm.java (hunk 4 above)
Comment (fidransky) [reply discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/form/TopicForm.java]: Well, the same todo is everywhere `AccessDeniedException` is caught. It was not my focus in this PR.

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java (hunk 5 above)
Comment (fidransky) [reply discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java]: True.

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java (hunk 6 above)
Comment (fidransky) [reply discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/list/discussion/DiscussionListPanel.java]: True.

File: discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/panel/postReputation/PostReputationPanel.java (hunk 7 above)
Comment (fidransky) [reply discussment-ui-wicket/src/main/java/org/danekja/discussment/ui/wicket/panel/postReputation/PostReputationPanel.java]: True.
